### ISSUE TITLE
Investigate bulk automated docker builds

### ISSUE THREAD

**Issue by rjbrown57** [rjbrown57/binman#26]
Use binman to set up a build context and then build a docker container. The idea here would be to do very fast docker builds, possibly making use of go-containerregistry provided image rebasing.

```
- repo: helm/helm
  docker: 
    build: true
    dockerfile: path/to/custom/file # set a basic default otherwise
```
