### ISSUE TITLE
Allow sources to track for new versions other than github.

### ISSUE THREAD

**Issue by rjbrown57** [rjbrown57/binman#27]
Allow sources to track for new versions other than github. E.G gitlab.

This would need to be part of a larger refactor to move to a more "plugin" style for how your versions are tracked.

**Comment by rjbrown57** [comment]
https://github.com/xanzy/go-gitlab

**Comment by rjbrown57** [comment]
# gitlab package

* Refactor config to include "source". Example config below. Default behavior is still to query github.com. 
* Add ability to specifcy sources in config. Defaults will include github/gitlab public. 
```
config:
  sources:
    gitlab:
      tokenvar: GL_TOKEN
      url: gitlab.com
      apitype: gitlab
    github:
      tokenvar: GH_TOKEN
      url: github.com
      apitype: github
    github.mycompany.com:
      tokenvar: GH_TOKEN
      url: gh.mycompany.com
      apitype: github
    gitlab.mycompany.com:
      tokenvar: MGL_TOKEN
      url: https://mygitlab
      apitype: gitlab
      #insecure: bool // maybe?
```

Add multiple ways to select source
1. using source key
2. using full name in repo that matches configured source

```
config:
  # See above
releases:
  - repo: anchore/syft # Basic github sync
  - repo: gitlab-org/cli/
    source: gitlab.com # specify source with source keyword
  # source in name support
  - repo: gitlab.com/gitlab-org/cli 
  - repo: mycoolproject/cli/
    source: gitlab.mycompany.com
  - repo: mycoolproject/ghproject/
    source:  github.mycompany.com
```

When this work is done we can create the "gl" package and required actions. GL will work nearly identicaly to GH.

test projects
* https://gitlab.com/gitlab-org/cli/-/releases
