### ISSUE TITLE
Allow custom post-step execution via config

### ISSUE THREAD

**Issue by rjbrown57** [rjbrown57/binman#30]
Currently we handle all post Download steps. Add config to allow custom post Download steps.

This could allow tracking of something like golang/go to keep your go installation up to date. This should be written in a way to be highly flexible as to what is actually done. This could likely be part of a larger refactor of how binman progresses through it's phases.

```
  - repo: golang/go
    url: https://go.dev/dl/go{{ trimPrefix "go" . }}.linux-amd64.tar.gz
    downloadOnly: true
    postSteps:
      executor: /bin/bash
      do: myscript here
```  
  
  https://go.dev/doc/install # install docs here
