### ISSUE TITLE
Add ability to change directories in a post command

### ISSUE THREAD

**Issue by rjbrown57** [rjbrown57/binman#65]
Possibly add `dir:` to command struct, to set current directory for execution? Currently commands will be executed from wherever you invoke binman.
 
```
releases:
 # Some repos do not publish assets, via github or external url. In such a case you could use the below to get the binary via go get"
    - repo: google/gops
      postonly: true
      postcommands:
      - command: go
        args: ["get","github.com/google/gops"]
        dir: "/tmp/mydir/
      - command: cp
        args: ["/home/user/go/bin/gopls","/home/user/binMan/repos/{{ .org }}/{{ .project }}/{{ .version }}"]
```
