### ISSUE TITLE
Unable to open DB starting on v0.10.0

### ISSUE THREAD

**Issue by marcciosilva** [rjbrown57/binman#85]
Hi! This is more of a question.
I have the following Dockerfile:
```dockerfile
FROM ghcr.io/rjbrown57/binman:v0.9.2 AS binman

COPY ./binman.runner /config

RUN binman -c /config && ls -l /bins
```
`binman.runner` is just a binman config file like the following:
```
config:
  releasepath: /bins
  upx:
    enabled: false
    args: []
releases:
- repo: kubernetes/kubernetes
  url: "https://dl.k8s.io/release/{{.version}}/bin/{{.os}}/{{.arch}}/kubectl"
  linkname: kubectl
```

Now, if I try to build a Docker image with this Dockerfile starting on binman's version v0.10.0, I get the following error when the `binman` command is ran:
```
 > [3/3] RUN binman -c /config && ls -l /bins:
0.341 time="2024-01-03T18:01:37Z" level=fatal msg="Unable to open DB - open /root/.config/binman/binman.db: no such file or directory"
```

This didn't happen on v0.9.2 for example (image built just fine) - is there some extra setup required from v0.10.0 onwards for the DB to be setup correctly when using binman like this?
